baseURL = '/'
languageCode = 'en-us'
title = 'evolvingkid, My little blog'
theme = "mini"


[params]
author= 'evolvingkid'
bio = 'Software Engineer at Tortoise'

[markup]
    [highlight]
    guessSyntax = 'true'
    style = 'emacs'

[social]
github = 'https://github.com/evolvingkid'
twitter = 'https://twitter.com/evolvingkid'
